language: node_js
node_js:
- 6.11.2
install:
- npm install && npm run-script build
deploy:
  provider: s3
  access_key_id:
    secure: "uNZU0hI8D42gRu96zq9XGfWuLMUG4xe2XwTr4RucW5hvSrqeJmzrE/bBgMnbGLUr2PTzNLlE6aaLSZPFBklYM4SSwOgs08SQEQ/DMsBIAorhwVWu3PwNTglj9CV+Y0fG/MuXHcEfet6KMbzuS0qN1Q/cR+6NOHAnoYsCoc9pAsK8r1oCUVe6f3QKrtenduXc4yoCmGYq6wOE/VSvNrH7eDTjaUmBQfZ/kPcqE0xfaz4fkD0Dz5EE+JYNWwo/GWnRL2uNhQYrJcYtvy50P2zZB2R/HL+AEBVS9fMu/S9V77WHiS24VOf6M/mX8MyQ2Z0NpTL+ljc/nopmsRGGo3P4tM2KhzvpS4L0N2nAZbF/tcw1xC5q94kO4CLjADxBxzTn1NdrZo/q157eqauTT0lcbPKPLwDukbzWByrbPsximvWkkRkLzUWkbOw5byYHdJTck9VE1eiqdSIsUrREnB3x+yRxOEnwJxR28vXA1FqO4wBfQAoDE7nmTnvrMPTIkjUerOg+C0jWDoGyZ7DuCJut/xXBStYPqiosrE5mM4COY0/DjfWKkhaXr9uyCUvhuVCvMK2t2Ei8Agji+R1drbOaO9eZYZt5zyiz0s/uEiF7GQh2ty4Wfqv8hnQScZNIMxdJb4B+hJDIHy13bxyTzxjd96j4/b4JCfDOZGY0auYRyxo="
  secret_access_key:
    secure: "caE2MJhrCu3U0HsUIEWykOHeqDjAl5AxEpck4oLINR/CAejeiZZ0e0mJxk8eTBz8YfmFjTnblakTLGvfA2bWOV0jE6l1vE8zmRK3sCydAp/ZHkidH4UnO49HScqAn5AqHmceC+G9Ox2zKtK/FNS2y4qdKwzh71bUvmkrpKYFoe2F8GR/hemkwHxDGKbvsRODku+/zOk6PNyrQFva8LB3i7zjSl2Ruv+CgOBNPO2YuBG8Dlx8b1BCWKbw9MwbufuDBFH5Skb9ZsP6CjGlZprtni5PEVX/I2PWxRHmAdnZN/TXyiblEWJg8UHgiTndDZNgooqVPouD+OpGhX4T/fVtMIYdHqkWIrDrufrZJ2oLBbiESSf6tFWk090AnIfsrWrgyhlqhvov+zZ5WxIrXgaLtpXRF5w4loMRSiFrjObVPYEtT5pxiRxnAtSiV2fjdd3w376EVJ7S0aLp8XwC/xv/Z8iQAm8pAs3ngsDdQALNwHss4yV7LF8D60cl5HcEoPS2rgZ29dq6rqpHIhrQy7sBVaB79DTDr1qIn8n85fbUK8rIbIbr3RPvSEsRdfNV12nN7C1CZ19qim44Sycl/ECbKv6FPYAR3KBISM9wW0esEoMoGLNYW2JMHG9lUkAWXu/DXuF6Xv/8fYytVXik+vN+fyhF7L1aa1nsJ7k007owqsE="
  local-dir: public
  bucket: joshbutcher.io
  skip_cleanup: true
  on:
    branch: master
