language: node_js
node_js:
- 6.11.2
install:
- npm install && npm run-script build
deploy:
  provider: s3
  bucket: joshbutcher.io
  skip_cleanup: true
env:
  global:
  - secure: aKSXrE8PKf61sjOA0IpeJ9TBcJij5Xm810Q6loOB2o2SYFutbm3ga6FyWnkFDeELcid+GGyIwMn+SIHeqAhmi+RzOxg3KH+FYeSjFA96P04ZkJR52Sfse2Xykof4rDyDQx7UFN4b8y7+wml9BFJ0mgGykH5IiqIlTJ1zQBBg7E/beH5ZSvfx8Jb1kNLbsax/k+G3gCj8f7ej0n9cMN/GMwcu89nLVo9+/N8QgC/XVlxoDdh7RbkMG4mlaMx86rCyfn34g6rI8uyYsRGynbXfGL6WrRhHEj6UZpe7mTeGmZSUam7JMG1g6JTvHsWnDYYp0KPfnI8GILqT7pA5O3W9FMFOvoubjx95hUqAquO7rUaGyBwWPyGtmccUCHpibx30NFHkLxZ8xf4GN1ru3C1CecehiR//H2hK958O6C2nfRIGQ8vvT+6RCQTtih4jD3/cSkcxiDw1a+aiMV/jzZEsw7oj62mPwX3RvM4mWk4q7rFnc4c3mjXdrEUNbEfMAOShYIXOzornYERsxj/uyKyfZ/sa9uZSUj945LK3f6A6kd4CgYnWjTK56x8V//LEBJjaes5pP5R7j+il3MLcrbz0UROfgAjt63uIf8W0eE7/UvgL1jr8r+iznAlxthUsVICr3miaAP1AZEQSoufrPvn2O9KILQXtn8arJKDZvnGsa8w=
  - secure: hDqrHtjnyaHUGPQ+hqYPaXC3HaXBEdeKVcugn0g6ogLFAZxAryMJQqY0HjufnAvjhcEsontEKDlsa/r0vqvo9xX3I3pOKzkwCMLjJQ+4JZ7wImOttEBCRqNrMviqXXSTLSzcFce+UXL9VnMfHGzIarHTDO5OxHmYPchT1t7AMlJG1JCv5wAIG9m8uuhwhGmrxNpa+kpUkP0HeHWTGGQ9vH/fsd61qlzvv63mPHD0dUrQFB+F9yPQypqhsJd5k2qUAbB78Ylnqrrkbh6jFGfOxBxNTIZSB+4kWA0kVTBukmbw5YXbdQ+/jj7Y4S+uoaB6EhigG9b2K6//V5WSgH6/tRPQNfxnXl26eLalaDMcmdVpFjRYYcTy/18kncAQt2na0jjghE3j7xYZ6iipNtxmbxnbG8O2lEbItEzT6Hm652lyIzvwLgjOuSbztiD6Mi0ki/TqALf0Q69mg3AoYnBi3xRhsjsT44nEZDVrbzgo8B1fc6HBz7rgq7GWptt0UVDz6TSgOAqiAdzh2/UsQoXDiudmhGOKjfA4yRhaA89QAPLUYkcTgYj/btmCX2o6p0svwFV3M7UMZhRqdKbXRiNFHqkCRuatgFn586kn6xkPvfDTy+TC5rt9zgkg2yY3voq/Z2SxiFIwbcq6mxQqwdLdygovxa5FMKFE4N2LrxB6fnQ=
