language: node_js
node_js:
 - "6.11.2"

install:
  - npm install && npm run-script build

deploy:
  provider: s3
  access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['AWS_SECRET_KEY'] %>
  local-dir: public
  bucket: "joshbutcher.io"
  skip_cleanup: true
  on:
    branch: master
