sudo: required
language: node_js
node_js:
- 6.11.2
python:
- '2.7'
cache:
- pip
install:
- npm install && npm run-script build
- sudo pip install awscli
branches:
  only:
  - master
deploy:
  provider: s3
  access_key_id:
    secure: NanuUFDdV/UuvTdbRupEPpxdk6LiDtKxLmCk8GPnCzQyoV3KRuWESV+bD+kfnL3vq6u42XxOyfXKysDpvuDWdCjt3F5kP5X3p1VpEn9iGPg4+ToyaRpLhP1FfbRtuLURjjUTs5sYkSd6xIWvz/o9w4iPR4l0Wa0cNNi4W1F+QgDh2Gk1Pr8W6umKA9vU6SuyTkoNvbugUgrViNGbfS1y9lvoOOmyOaGZtufeEJsYygYYiCVt3eTQgd4m+9fpPdPAXgondoW8TvD7DTwAe4pFGywuNRl4Xl5QS//TeWmgPVz/YJEUidbF+SzsTCp6bgZA9kNUDa7T9GEOe2Kv0XF/hS67eL8OA4oxCeV8JhVj5hTiqggl10+E6RaERGElxJ1uCKffIZpHjhgE75R+z2MhYrJJMl6GGn+DwwYpdodkz1pj8P/FzQtGwLMeUCSX/0BeohxdWYFxInOA4Vn1zL2Xc+mPUoP6qkr5KUifBVWjcQ3UGrb8CccAvU/MZZpPts7F1NbSHJGylq8qUfd20oF16g7DtxPLVnFLCkHZCDyKUrOpjs1xB0NoJ8P3KvkcS+chURJgn/Ath35PP3jnR/CgpJoZtklspTZ4qFG8KkBxT5/5GRfVun7dPzp+InbCuqFDRBbQaW14MEF4mm/HVP36bE/JD2iyH2SKwh2LYe2zXL4=
  secret_access_key:
    secure: gMzsZNZ4L+qatZbLNI/pgO/7SHAXMkevJHQbXPU+cbH0xcLcq3+aTCVdHQqCbKguqylS/s63CEs8udqAFRljS38qrI37s9D+Unvdc6hMcgfI8TqOsj2VtkwzeSdxYubeKp4HycAgFKyzpH5MovQ6B6TVB7wpsALodqWHsWT6m6yaePOfiPdfKD64botohqwya5leEwGHq9aD3eTovmFRb/n12XeByN15yzTB8bLNwRyjZEfDgfTJ2jpEsfHu/VugHnRRrDuFikEQ1soyuMLr1MNJyg/BZbICa6oWXeVbxViTGdstYrej0ASgzktT24ORn2quIeyRHfI7QrVmG1MT7P+DBRIyuSUt/6PPZ6SJw+2u3tYikPBeixJcAW/EaK+53hJxOlOfFoYY9gK/CN85puk6MdkKyH1ST3g80Mypy2WgbTOUYALaLO1lonxT66/rqhJK9rNCswu62pkKxtzuBEzeq34gLbCZLp3xZXdBV4FBJwGCyMS00ADQMkEFERAg7Yyd6+/FrWwU0kIhY5PgM1rrj0WJXtIdopUD7LpcK4AzQmg13yZdTZMTJeB6zPTGLSDcFsKk7bO+k771T22tsk+yBM7lYqy4qH2VmJ+h2O5BkWETpWX6khmiLgToygm/6p2fZJfwW3tvzkXHIVgPMo7VafSpchSPiIz2EDtxkVM=
  bucket: joshbutcher.io
  skip_cleanup: true
  region: us-east-1
  local_dir: public
  cache_control: max-age=2160
  on:
    branch: master
after_deploy:
- aws configure set preview.cloudfront true
- aws cloudfront create-invalidation --distribution-id EB1ZESPETMGXW --paths "/*"
env:
  global:
    secure: ncB2OU48pW7q1ZUQlh9zWkSOBEm5kc+t1bnaBevrw82dgt2e3l1C0o2lnF1sLs+uM0AZHzqOnEyP5j1qFzopSJlBeH8Fht3Gial8zaKZDDoRE8tDrEZu0upvYNSPh0DmIECwf8jYCkyVgHyamMlXoh9nXzSwt9q0rxwAhZ4fa3EJoNkS7gxyjdSeudQ+ZayKnZxK1irc5UG9b9yzeSfrZRCmhgsPNVVHAi4BSdfmswUs99+seizbxBuGkGLJis9mxYY1ixghnRGBKcHrjtNNUUAYthY62bgOTdOF5eSy6LTIJ7H6oxN+2Hh6psSOfI9XUuBQvB7F8VJJZVMzdd9qBtV02GC9cc4WjTlE4L/sQ1Ev+km54lCqym468mn2FwtaKed7i2l3XB36scR85ghYrUeaTAb833cBSBxL5cQcMEheIngTl7IuiBWyi1UhOf5eZn9fM/DIfBbzNTqG7lAagshi5GZSmjBfw+MoW+9qZFRBqvOJxWIEEeAiaFoZol+yFsxUCNu0q/XgungJsBUrjmdfo/ShqkBxdkcBV51UD7gumLMyGBKtow++BFsz7tHgRqbQshbYzcSd6qkboSvqWPqIp6ubyZ7OFPbxjJrokVi+Jqr84vOV4yjNgNurnJDFE0bX/vCCRG5PuwT7fwWTl9gJ7EXfkYU2D0zNQiOBHA8=
