export const icons = {
  js: require("styles/icons/javascript-plain.svg"),
  python: require("styles/icons/python-original.svg"),
  react: require("styles/icons/react-original.svg"),
  django: require("styles/icons/django-original.svg"),
  mongo: require("styles/icons/mongodb-original.svg"),
  postgres: require("styles/icons/postgresql-original.svg"),
  docker: require("styles/icons/docker-original.svg"),
  nginx: require("styles/icons/nginx-original.svg"),
  mysql: require("styles/icons/mysql-original.svg"),
  node: require("styles/icons/nodejs-original.svg"),
  sass: require("styles/icons/sass-original.svg"),
  webpack: require("styles/icons/webpack-original.svg"),
  apache: require("styles/icons/apache-original.svg"),
  aws: require("styles/icons/amazonwebservices-original.svg"),
  html: require("styles/icons/html5-original.svg"),
  jquery: require("styles/icons/jquery-original.svg"),
};
